modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="rimine"
version="${version}"
displayName="Rimine"
authors="vkkkv"
description='''
Rime Input Method for Minecraft.
'''

[[dependencies.rimine]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rimine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
